// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleTemplate.Models;

namespace SampleTemplate.Migrations
{
    [DbContext(typeof(PortoDbContext))]
    [Migration("20220221104207_studentad")]
    partial class studentad
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SampleTemplate.Models.Slider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClothType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TrendWord")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClothType = "On Jackets",
                            DisCount = "Get up to 60% off",
                            Image = "slide1.jpg",
                            Price = 130,
                            TrendWord = "Winter Fashion Trends"
                        },
                        new
                        {
                            ID = 2,
                            ClothType = "On Coat",
                            DisCount = "Get up to 10% off",
                            Image = "slide2.jpg",
                            Price = 200,
                            TrendWord = "Season Fashion Trends"
                        });
                });

            modelBuilder.Entity("SampleTemplate.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SampleTemplate.Models.StudentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentAddress");
                });

            modelBuilder.Entity("SampleTemplate.Models.StudentAddress", b =>
                {
                    b.HasOne("SampleTemplate.Models.Student", "Student")
                        .WithOne("Adress")
                        .HasForeignKey("SampleTemplate.Models.StudentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SampleTemplate.Models.Student", b =>
                {
                    b.Navigation("Adress");
                });
#pragma warning restore 612, 618
        }
    }
}
