//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityBegin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AkademiyaEntities : DbContext
    {
        public AkademiyaEntities()
            : base("name=AkademiyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudendsInfo> StudendsInfoes { get; set; }
    
        public virtual ObjectResult<SumInfo_Result> SumInfo(Nullable<int> sum)
        {
            var sumParameter = sum.HasValue ?
                new ObjectParameter("sum", sum) :
                new ObjectParameter("sum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SumInfo_Result>("SumInfo", sumParameter);
        }
    }
}
