//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityBegin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudendsInfo
    {
        public string Telebe { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Qrup { get; set; }
    }
}
